"""
Forecast Repository for SupplySense AI.

Handles database operations for storing, querying, and managing downstream ML
forecast predictions generated by pipeline executions in MySQL.
"""

import os
import sys
import logging
import datetime
from typing import List, Dict, Any, Optional, Union
import pandas as pd

# Ensure repository root is on sys.path
REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '../../'))
if REPO_ROOT not in sys.path:
    sys.path.insert(0, REPO_ROOT)

from common.database import get_connection

logger = logging.getLogger(__name__)


def save_forecast_results(
    execution_id: int,
    pipeline_name: str,
    predictions: Union[pd.DataFrame, List[Dict[str, Any]], str],
    model_name: str = "XGBoost",
    model_version: str = "xgboost-v1",
    connection=None
) -> int:
    """
    Persists forecast predictions into the `forecast_results` table in MySQL.

    Supports DataFrame, list of dictionaries, or CSV file path.
    Standardizes column names and inserts records using an idempotent batch query
    (INSERT IGNORE or ON DUPLICATE KEY UPDATE).

    Args:
        execution_id: ID of the pipeline_executions record.
        pipeline_name: Name of the executed pipeline.
        predictions: DataFrame, list of dicts, or CSV path with forecast predictions.
                     Expected keys/columns:
                       - 'product_category'
                       - 'week_start_date' or 'forecast_week'
                       - 'predicted_demand'
        model_name: Model identifier (default: 'XGBoost').
        model_version: Model version identifier (default: 'xgboost-v1').
        connection: Optional open PyMySQL database connection.

    Returns:
        int: Number of rows successfully inserted.

    Raises:
        ValueError: If predictions data is invalid or empty.
        Exception: If database insertion fails.
    """
    # 1. Parse input predictions into standardized records
    df = None
    if isinstance(predictions, str):
        if not os.path.isfile(predictions):
            raise FileNotFoundError(f"Predictions file not found at: {predictions}")
        df = pd.read_csv(predictions)
    elif isinstance(predictions, pd.DataFrame):
        df = predictions.copy()
    elif isinstance(predictions, list):
        if not predictions:
            logger.warning("Empty list of predictions provided to save_forecast_results.")
            return 0
        df = pd.DataFrame(predictions)
    else:
        raise ValueError("Unsupported predictions format. Must be DataFrame, list of dicts, or CSV file path.")

    if df.empty:
        logger.warning("Predictions DataFrame is empty. No forecast rows to save.")
        return 0

    # Robustly resolve column names across DataFrame
    def find_col(candidates):
        for c in candidates:
            if c in df.columns:
                return c
        return None

    cat_col = find_col(['product_category', 'category', 'product_id'])
    week_col = find_col(['forecast_week', 'week_start_date', 'week', 'date'])
    pred_col = find_col(['predicted_demand', 'forecast', 'prediction', 'predicted_value'])

    missing = []
    if not cat_col:
        missing.append('product_category')
    if not week_col:
        missing.append('forecast_week (or week_start_date)')
    if not pred_col:
        missing.append('predicted_demand')

    if missing:
        raise ValueError(f"Predictions missing required column(s): {', '.join(missing)}")

    # Prepare values tuple for batch execution
    insert_records = []
    for _, row in df.iterrows():
        cat = str(row[cat_col])
        raw_week = row[week_col]
        if isinstance(raw_week, (pd.Timestamp, datetime.datetime, datetime.date)):
            f_week = raw_week.strftime('%Y-%m-%d')
        else:
            f_week = str(raw_week)[:10]

        pred_val = float(row[pred_col])
        insert_records.append((
            execution_id,
            pipeline_name,
            cat,
            f_week,
            pred_val,
            model_name,
            model_version
        ))

    if not insert_records:
        return 0

    should_close = False
    if connection is None:
        connection = get_connection()
        should_close = True

    query = """
        INSERT INTO forecast_results (
            execution_id,
            pipeline_name,
            product_category,
            forecast_week,
            predicted_demand,
            model_name,
            model_version
        ) VALUES (%s, %s, %s, %s, %s, %s, %s)
        ON DUPLICATE KEY UPDATE
            predicted_demand = VALUES(predicted_demand),
            model_name = VALUES(model_name),
            model_version = VALUES(model_version),
            created_at = CURRENT_TIMESTAMP
    """

    cursor = connection.cursor()
    try:
        cursor.executemany(query, insert_records)
        connection.commit()
        inserted_count = cursor.rowcount
        logger.info(
            f"Saved {len(insert_records)} forecast predictions for execution #{execution_id} "
            f"({model_name} {model_version}). Affected rows: {inserted_count}."
        )
        return len(insert_records)
    except Exception as exc:
        logger.error(f"Failed to persist forecast results for execution #{execution_id}: {exc}")
        if connection:
            connection.rollback()
        raise
    finally:
        cursor.close()
        if should_close and connection:
            connection.close()


def get_forecasts_by_execution_id(
    execution_id: int,
    connection=None
) -> List[Dict[str, Any]]:
    """
    Retrieves all forecast records for a specific execution ID.

    Args:
        execution_id: ID of the pipeline execution.
        connection: Optional open PyMySQL database connection.

    Returns:
        List of dictionaries with forecast records.
    """
    should_close = False
    if connection is None:
        connection = get_connection()
        should_close = True

    cursor = connection.cursor()
    try:
        cursor.execute("""
            SELECT forecast_id, execution_id, pipeline_name, product_category,
                   forecast_week, predicted_demand, model_name, model_version, created_at
            FROM forecast_results
            WHERE execution_id = %s
            ORDER BY forecast_week ASC, product_category ASC
        """, (execution_id,))
        return cursor.fetchall()
    finally:
        cursor.close()
        if should_close and connection:
            connection.close()


def get_forecasts_by_category(
    product_category: str,
    limit: int = 50,
    connection=None
) -> List[Dict[str, Any]]:
    """
    Retrieves forecast records for a specific product category.

    Args:
        product_category: Name of the product category.
        limit: Max records to return (default: 50).
        connection: Optional open PyMySQL database connection.

    Returns:
        List of dictionaries with forecast records.
    """
    should_close = False
    if connection is None:
        connection = get_connection()
        should_close = True

    cursor = connection.cursor()
    try:
        cursor.execute("""
            SELECT forecast_id, execution_id, pipeline_name, product_category,
                   forecast_week, predicted_demand, model_name, model_version, created_at
            FROM forecast_results
            WHERE product_category = %s
            ORDER BY forecast_week DESC, created_at DESC
            LIMIT %s
        """, (product_category, limit))
        return cursor.fetchall()
    finally:
        cursor.close()
        if should_close and connection:
            connection.close()


def get_forecasts_by_week(
    forecast_week: Union[str, datetime.date],
    limit: int = 50,
    connection=None
) -> List[Dict[str, Any]]:
    """
    Retrieves forecast records for a specific week.

    Args:
        forecast_week: Forecast week date (YYYY-MM-DD string or datetime.date).
        limit: Max records to return (default: 50).
        connection: Optional open PyMySQL database connection.

    Returns:
        List of dictionaries with forecast records.
    """
    should_close = False
    if connection is None:
        connection = get_connection()
        should_close = True

    if isinstance(forecast_week, (datetime.datetime, datetime.date)):
        forecast_week = forecast_week.strftime('%Y-%m-%d')
    else:
        forecast_week = str(forecast_week)[:10]

    cursor = connection.cursor()
    try:
        cursor.execute("""
            SELECT forecast_id, execution_id, pipeline_name, product_category,
                   forecast_week, predicted_demand, model_name, model_version, created_at
            FROM forecast_results
            WHERE forecast_week = %s
            ORDER BY product_category ASC
            LIMIT %s
        """, (forecast_week, limit))
        return cursor.fetchall()
    finally:
        cursor.close()
        if should_close and connection:
            connection.close()


def get_recent_forecasts(
    limit: int = 50,
    connection=None
) -> List[Dict[str, Any]]:
    """
    Retrieves most recent forecast records.

    Args:
        limit: Max records to return (default: 50).
        connection: Optional open PyMySQL database connection.

    Returns:
        List of dictionaries with recent forecast records.
    """
    should_close = False
    if connection is None:
        connection = get_connection()
        should_close = True

    cursor = connection.cursor()
    try:
        cursor.execute("""
            SELECT forecast_id, execution_id, pipeline_name, product_category,
                   forecast_week, predicted_demand, model_name, model_version, created_at
            FROM forecast_results
            ORDER BY created_at DESC, forecast_id DESC
            LIMIT %s
        """, (limit,))
        return cursor.fetchall()
    finally:
        cursor.close()
        if should_close and connection:
            connection.close()


def get_forecast_summary_by_execution(
    execution_id: int,
    connection=None
) -> Dict[str, Any]:
    """
    Calculates summary aggregate statistics for an execution's forecasts.

    Args:
        execution_id: ID of the pipeline execution.
        connection: Optional open PyMySQL database connection.

    Returns:
        Dict with summary stats (total_forecasts, distinct_categories, min_week, max_week, avg_demand).
    """
    should_close = False
    if connection is None:
        connection = get_connection()
        should_close = True

    cursor = connection.cursor()
    try:
        cursor.execute("""
            SELECT COUNT(*) AS total_forecasts,
                   COUNT(DISTINCT product_category) AS distinct_categories,
                   MIN(forecast_week) AS min_week,
                   MAX(forecast_week) AS max_week,
                   AVG(predicted_demand) AS avg_predicted_demand,
                   MIN(model_name) AS model_name,
                   MIN(model_version) AS model_version
            FROM forecast_results
            WHERE execution_id = %s
        """, (execution_id,))
        result = cursor.fetchone()
        return result or {}
    finally:
        cursor.close()
        if should_close and connection:
            connection.close()
